apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  externalIPs: 
  - 172.20.84.22
  - 10.62.13.152
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  externalIPs: 
  - 172.20.84.22
  - 10.62.13.152