{
 "title": "Confidence Alerting",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "model",
    "query": "label_values(confidence_sum, model)"
   },
   { "name": "pred", "label": "Prediction", "query": "label_values(pred_class)" },
   {
    "name": "client_ip",
    "label": "AOI ip",
    "query": "label_values(confidence_sum, userip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Alter by variables above",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$model $pred Confidence of $client_ip",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(confidence_sum{model=~\"$model\",pred_class=~\"$pred\",userip=~\"$client_ip\"}[2h])/increase(images_total{model=~\"$model\",pred_class=~\"$pred\",userip=~\"$client_ip\"}[2h])",
       "legendFormat": "{{userip}}"
      }
     ]
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "capacitor_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"capacitor\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"capacitor\", pred_class=\"OK\"}[3h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"capacitor\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"capacitor\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "capacitorwrong_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"capacitorwrong\", pred_class=\"OK\"}[4h]))/sum without (userip) (increase(images_total{model=\"capacitorwrong\", pred_class=\"OK\"}[4h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "connector_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"connector\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"connector\", pred_class=\"OK\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"connector\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"connector\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "screw_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"screw\", pred_class=\"OK\"}[15h]))/sum without (userip) (increase(images_total{model=\"screw\", pred_class=\"OK\"}[15h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"screw\", pred_class=\"NG\"}[15h]))/sum without (userip) (increase(images_total{model=\"screw\", pred_class=\"NG\"}[15h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "label_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"label\", pred_class=\"OK\"}[15h]))/sum without (userip) (increase(images_total{model=\"label\", pred_class=\"OK\"}[15h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"label\", pred_class=\"NG\"}[15h]))/sum without (userip) (increase(images_total{model=\"label\", pred_class=\"NG\"}[15h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "heatsink_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"heatsink\", pred_class=\"OK\"}[4h]))/sum without (userip) (increase(images_total{model=\"heatsink\", pred_class=\"OK\"}[4h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"heatsink\", pred_class=\"NG\"}[4h]))/sum without (userip) (increase(images_total{model=\"heatsink\", pred_class=\"NG\"}[4h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "buzzer_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"buzzer\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"buzzer\", pred_class=\"OK\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"buzzer\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"buzzer\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "cpuskt_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"cpuskt\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"cpuskt\", pred_class=\"OK\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"cpuskt\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"cpuskt\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "jumper_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"jumper\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"jumper\", pred_class=\"OK\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"jumper\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"jumper\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "jumper_head_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"jumper_head\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"jumper_head\", pred_class=\"OK\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"jumper_head\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"jumper_head\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "UID_confidence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"uid\", pred_class=\"OK\"}[2h]))/sum without (userip) (increase(images_total{model=\"uid\", pred_class=\"OK\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "sum without (userip) (increase(confidence_sum{model=\"uid\", pred_class=\"NG\"}[2h]))/sum without (userip) (increase(images_total{model=\"uid\", pred_class=\"NG\"}[2h]))",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  },
  {
   "title": "Confidence_Sum",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(confidence_sum{model=\"Final\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"Final\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"Final\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"Final\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"buzzer\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"buzzer\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"buzzer\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"buzzer\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"connector\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"connector\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"connector\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"connector\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"cpuskt\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"cpuskt\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"cpuskt\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"cpuskt\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"label\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"label\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"label\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"label\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"heatsink\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"heatsink\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"heatsink\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"heatsink\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"jumper\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"jumper\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"jumper\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"jumper\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"jumper_head\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"jumper_head\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"jumper_head\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"jumper_head\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"screw\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"screw\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"screw\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"screw\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"capacitor\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"capacitor\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"capacitor\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"capacitor\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"capacitorwrong\", pred_class=\"NG\"}[2h])/increase(images_total{model=\"capacitorwrong\", pred_class=\"NG\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    },
    {
     "expr": "increase(confidence_sum{model=\"capacitorwrong\", pred_class=\"OK\"}[2h])/increase(images_total{model=\"capacitorwrong\", pred_class=\"OK\"}[2h])",
     "legendFormat": "{{model}}_{{pred_class}}"
    }
   ]
  }
 ]
}