{
 "title": "FTP Daily Metrics",
 "description": "project: aoi-wzs-p3-dip-prewave-saiap",
 "tags": [
  "aoi-wzs-p3-dip-prewave-saiap",
  "daily-metrics",
  "Overkill",
  "Leak"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "line",
    "label": "產線",
    "query": "label_values(metrics_true_ok{job=\"ftp-metrics\"},line)"
   },
   {
    "name": "date",
    "label": "日期",
    "query": "label_values(metrics_true_ok{job=\"ftp-metrics\"},date)"
   },
   {
    "name": "component",
    "label": "元件",
    "query": "label_values(filename_of_overkill{job=\"ftp-metrics\"},comp)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n* **time range at right top of this dashboard represents the inclusion of metrics refreshed ( better to be `last 1 hour`, which is the latest refresh )**"
  },
  {
   "title": "All Image Quantity",
   "type": "stat",
   "description": "sum(metrics_true_ng) + sum(metrics_true_ok)",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(metrics_true_ng{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) + (sum(metrics_true_ok{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)))"
    }
   ]
  },
  {
   "title": "Overkill Image Quantity",
   "type": "stat",
   "description": "metrics_false_ng",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_false_ng{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"})"
    }
   ]
  },
  {
   "title": "Overkill Rate (%)",
   "type": "gauge",
   "description": "sum(metrics_false_ng) / (sum(metrics_true_ng)+sum(metrics_true_ok))",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(metrics_false_ng{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) / ((sum(metrics_true_ng{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) + (sum(metrics_true_ok{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)))"
    }
   ]
  },
  {
   "title": "Leak Image Quantity",
   "type": "stat",
   "description": "metrics_false_ok",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_false_ok{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"})"
    }
   ]
  },
  {
   "title": "Leak Rate (%)",
   "type": "gauge",
   "description": "sum(metrics_false_ok) / (sum(metrics_true_ok)+sum(metrics_true_ng))",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(metrics_false_ok{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) / ((sum(metrics_true_ng{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) + (sum(metrics_true_ok{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)))"
    }
   ]
  },
  {
   "title": "Inverse Polarity Leak Image Quantity",
   "type": "stat",
   "description": "metrics_inversepolarity_leak",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_inversepolarity_leak{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"})"
    }
   ]
  },
  {
   "title": "Inverse Polarity Leak Rate (%)",
   "type": "gauge",
   "description": "sum(metrics_inversepolarity_leak) / (sum(metrics_true_ok)+sum(metrics_true_ng))",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(metrics_inversepolarity_leak{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) / ((sum(metrics_true_ng{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)) + (sum(metrics_true_ok{line=~\"$line\",date=~\"$date\",comp=~\"$component\",job=\"ftp-metrics\"}) OR on() vector(0)))"
    }
   ]
  }
 ]
}