{
 "title": "Loki Overkill & Leak Details",
 "description": "For showing Overkill & Leak log",
 "tags": [
  "Overkill",
  "Leak",
  "Log",
  "Loki"
 ],
 "time": { "from": "now-45d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "date",
    "label": "日期",
    "query": "query_result(count by (date)(count_over_time(metrics_true_ok{job=\"ftp-metrics\"}[1h])))"
   },
   {
    "name": "component",
    "label": "元件",
    "query": "query_result(count by (comp)(count_over_time(filename_of_overkill{job=\"ftp-metrics\"}[1h])))"
   },
   {
    "name": "overkill",
    "label": "Overkill Filename",
    "query": "query_result(count_over_time(filename_of_overkill{job=\"ftp-metrics\",comp=\"$component\",date=\"$date\"}[1h]))"
   },
   {
    "name": "leak",
    "label": "Leak Filename",
    "query": "query_result(count_over_time(filename_of_leak{job=\"ftp-metrics\",comp=\"$component\",date=\"$date\"}[1h]))"
   },
   {
    "name": "inversepolarity_leak",
    "label": "Inverse Polarity Leak Filename",
    "query": "query_result(count_over_time(filename_of_inversepolarity_leak{job=\"ftp-metrics\",comp=\"$component\",date=\"$date\"}[1h]))"
   },
   {
    "name": "overkill_img_url",
    "label": "Overkill Img Url",
    "query": "query_result(count_over_time(filename_of_overkill{job=\"ftp-metrics\",comp=\"$component\",date=\"$date\",filename=\"$overkill\"}[1h]))"
   },
   {
    "name": "leak_img_url",
    "label": "Leak Img Url",
    "query": "query_result(count_over_time(filename_of_leak{job=\"ftp-metrics\",comp=\"$component\",date=\"$date\",filename=\"$leak\"}[1h]))"
   },
   {
    "name": "inversepolarity_leak_img_url",
    "label": "Inverse Polarity Leak Img Url",
    "query": "query_result(count_over_time(filename_of_inversepolarity_leak{job=\"ftp-metrics\",comp=\"$component\",date=\"$date\",filename=\"$inversepolarity_leak\"}[1h]))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n* **time range at right top of this dashboard must include the date we want to look up**\n* **Showing nothing if selected label was None**"
  },
  {
   "title": "Overkill Predict Log ",
   "type": "table-old",
   "description": "$overkill",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{logger=\"predict\", filename=\"$overkill\"}"
    }
   ]
  },
  {
   "title": "Overkill Image",
   "type": "text",
   "description": "$overkill_img_url",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "content": "<img src='$overkill_img_url' width='300' height='250'>"
  },
  {
   "title": "Leak Predict Log ",
   "type": "table-old",
   "description": "$leak",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{logger=\"predict\", filename=\"$leak\"}"
    }
   ]
  },
  {
   "title": "Leak Image",
   "type": "text",
   "description": "$leak_img_url",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "content": "<img src='$leak_img_url' width='300' height='250'>"
  },
  {
   "title": "Inverse Polarity Leak Predict Log ",
   "type": "table-old",
   "description": "$inversepolarity_leak",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{logger=\"predict\", filename=\"$inversepolarity_leak\"}"
    }
   ]
  },
  {
   "title": "Inverse Polarity Image",
   "type": "text",
   "description": "$inversepolarity_leak_img_url",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "content": "<img src='$inversepolarity_leak_img_url' width='300' height='250'>"
  }
 ]
}