{
 "title": "INFA Gateway Metrics",
 "description": "project: aoi-ai",
 "tags": [
  "gateway",
  "oneai"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "MODEL_NAME",
    "query": "query_result(count by (model_name)(count_over_time(outline_img_counter_total{job=\"oneai-gateway\"}[$__range])))"
   },
   {
    "name": "pred_class",
    "label": "PRED_CLASS",
    "query": "query_result(count by (pred_class)(count_over_time(image_counter_total{job=\"oneai-gateway\"}[$__range])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "description": "requests count  \n(req_counter)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(req_counter_total{job=\"oneai-gateway\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total re-judged images",
   "type": "stat",
   "description": "re-judged images which are online component.  \n(total_inferred_img_counter_total)",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(total_inferred_img_counter_total{job=\"oneai-gateway\"}[$__range]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 0 },
   "content": "##### MUST SELECT LABEL `MODEL_NAME`\n↓↓↓↓↓"
  },
  {
   "title": "Image Amount",
   "type": "bargauge",
   "description": "within time range by component, pred_class. \nimage_counter_total",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(image_counter_total{job=\"oneai-gateway\"}[$__range])",
     "legendFormat": "{{ component }}: {{ pred_class }}"
    }
   ]
  },
  {
   "title": "TFserving Secs Taken",
   "type": "stat",
   "description": "(MUST SELECT MODEL_NAME).  \n\navg. tfserving secs taken by var: model_name.  \n(predicts_duration_secs / inferred_img_counter)",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(increase(predicts_duration_secs_total{job=\"oneai-gateway\",model_name=\"$model_name\"}[$__range])) / max(increase(inferred_img_counter_total{job=\"oneai-gateway\",model_name=\"$model_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Seconds taken per Image",
   "type": "gauge",
   "description": "The latest request secs taken during server processing.  \n(sec_perimg_Gauge)",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sec_perimg_Gauge" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 7 },
   "content": "##### MUST SELECT LABEL `MODEL_NAME`, `PRED_CLASS`\n↓↓↓↓↓"
  },
  {
   "title": "Seconds took per request",
   "type": "stat",
   "description": "seconds took per request by time range.   \n(pro_time_counter / req_counter_total)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(increase(pro_time_counter_total{job=\"oneai-gateway\"}[$__range])) / max(increase(req_counter_total{job=\"oneai-gateway\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average Model Confidence",
   "type": "stat",
   "description": "(MUST SELECT MODEL_NAME, PRED_CLASS)  \n\navg. model confidence by model_name, pred_class.  \n(confidence_sum / inferred_img_counter)",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(increase(confidence_sum_total{job=\"oneai-gateway\",model_name=\"$model_name\",pred_class=\"$pred_class\"}[$__range])) / max(increase(predicts_img_counter_total{job=\"oneai-gateway\",model_name=\"$model_name\", pred_class=\"$pred_class\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Seconds took per response image",
   "type": "stat",
   "description": "seconds took per response image by time range.     \n(pro_time_counter / total_res_img_counter)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(increase(pro_time_counter_total{job=\"oneai-gateway\"}[$__range])) / max(increase(total_inferred_img_counter_total{job=\"oneai-gateway\"}[$__range]))"
    }
   ]
  },
  {
   "title": "requests / min",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(req_counter_total[1m])) * 60"
    }
   ]
  },
  {
   "title": "images / min",
   "type": "graph",
   "description": "rate 1 min",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(image_counter_total{job=\"oneai-gateway\"}[1m])) by (component) * 60",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Confidence",
   "type": "graph",
   "description": "rate by 2 min",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(confidence_sum_total{job=\"oneai-gateway\",model_name!=\"own-cap-all\"}[2m]) / rate(predicts_img_counter_total{job=\"oneai-gateway\",model_name!=\"own-cap-all\"}[2m])",
     "legendFormat": "{{model_name}}-{{pred_class}}"
    }
   ]
  },
  {
   "title": "Model Health",
   "type": "graph",
   "description": "1: Healthy, 0: Offline  \nrequest get TF serving links.  \n(model_health)",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "health" }
   ],
   "targets": [
    { "expr": "model_health", "legendFormat": "{{model_name}}" }
   ]
  },
  {
   "title": "Errors Logs",
   "type": "logs",
   "description": "within time range",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{severity=\"error\"}"
    }
   ]
  },
  {
   "title": "Online Model Version ",
   "type": "graph",
   "description": "1: Healthy, 0: Offline.  \nmodel bar would be flexible if loaded new version model.  \n(:tensorflow:cc:saved_model:load_attempt_count)",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": ":tensorflow:cc:saved_model:load_attempt_count{job=\"oneai-tfserving\"}",
     "legendFormat": "{{model_path}}:{{status}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inference_version", "legendFormat": "{{model_name}}" }
   ]
  }
 ]
}