apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana.yaml
commonLabels:
  app: grafana
  role: monitoring
images:
- name: grafana/grafana
  newName: harbor.wzs.wistron.com.cn/datteam/grafana/grafana
  newTag: "7.0.0-ubuntu-custom"
configMapGenerator:
- name: grafana-config
  files:
  - ./grafana.ini