bases:
- ../../base
commonLabels:
  project: aoi-wzs-p3-dip-prewave-saiap
secretGenerator:
- name: cp-gitlab-access-token
  envs:
  - gitlab.txt
  type: Opaque
images:
- name: harbor.wzs.wistron.com.cn/datteam/aoi-wzs-p3-dip-prewave-saiap/gateway:latest
  newName: harbor.wzs.wistron.com.cn/datteam/aoi-wzs-p3-dip-prewave-saiap/gateway
  newTag: "2295b96d"
patchesStrategicMerge:
- externalIPs.yaml
- gitlab_clone_pull.yaml
- deployment_volume_volumeMounts.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "1.2"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 800Mi
  target:
    kind: Deployment
    name: gateway