apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
  - name: gw
    port: 3333
    targetPort: gw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway
        workingDir: /gw
        imagePullPolicy: "IfNotPresent"
        env:
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        ports:
        - name: gw
          containerPort: 3333
        readinessProbe:
          periodSeconds: 100
          httpGet:
            path: /metrics
            port: gw
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi