apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
# provisioner: kubernetes.io/gce-pd
# provisioner: rancher.io/local-path
provisioner: kubernetes.io/no-provisioner
# parameters:
#   type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer