apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - name: grafana
    port: 3000
    targetPort: dashboard
    nodePort: 30000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  serviceName: grafana
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: IfNotPresent
        args:
        - --config=/etc/grafana/grafana.ini
        envFrom:
        - secretRef: 
            name: grafana-env
        volumeMounts: 
        - mountPath: /var/lib/grafana
          name: data
        - name: grafana-config
          subPath: grafana.ini
          mountPath: /etc/grafana/grafana.ini
        - name: grafana-config
          subPath: grafana.yml
          mountPath: /etc/grafana/provisioning/datasources/grafana.yml
        - name: dashboard-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        ports:
        - name: dashboard
          containerPort: 3000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: dashboard
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: dashboard
      volumes: 
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: dashboard-config
        configMap:
          name: dashboard-config
      - name: dashboards 
        configMap:
          name: dashboards
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: "local-path"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi