apiVersion: v1
kind: Service
metadata:
  name: $containerprefix-gateway
  labels:
    prefix: $containerprefix
    app: gateway
    project: $projectcode
spec:
  type: NodePort
  externalIPs:
  - $aiserverip
  selector:
    prefix: $containerprefix
    app: gateway
    project: $projectcode
  ports:
  - name: gw
    port: 3333
    targetPort: gw
    nodePort: $gwnodeport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $containerprefix-gateway
  labels:
    prefix: $containerprefix
    app: gateway
    project: $projectcode
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      prefix: $containerprefix
      app: gateway
      project: $projectcode
  template:
    metadata:
      labels:
        prefix: $containerprefix
        app: gateway
        project: $projectcode
    spec:
      containers:
      - name: gateway
        image: $gatewayimage
        workingDir: /gw
        imagePullPolicy: Always
        env:
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "TRUE"
        ports:
        - name: gw
          containerPort: 3333
        livenessProbe:
          periodSeconds: 100
          httpGet:
            path: /metrics
            port: gw
        readinessProbe:
          periodSeconds: 100
          httpGet:
            path: /metrics
            port: gw
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: $limitscpu
            memory: $limitsmemory
        volumeMounts:
        - name: checkpoint-config
          subPath: Model_config
          mountPath: /config
        - name: checkpoint-config
          mountPath: /checkpoint
        - name: ai-predict
          mountPath: /AIpredict
      volumes:
      - name: checkpoint-config
        hostPath:
          path: $checkpointconfig
      - name: ai-predict
        hostPath: 
          path: $aipredict