apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mariadb.yaml
commonLabels:
  app: mariadb
images:
- name: mariadb
  newName: harbor.wzs.wistron.com.cn/datteam/mariadb
  newTag: "10.5.5"
- name: phpmyadmin
  newName: harbor.wzs.wistron.com.cn/datteam/phpmyadmin
  newTag: "latest"