apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  externalIPs: 
  - 172.30.52.10 
  - 10.41.16.21
  ports: 
  - nodePort: 30138
    port: 8080
    targetPort: phpmyadmin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        env:
        - name: PMA_HOST
          value: mariadb
        - name: PMA_PORTS
          value: "3306"
        - name: PMA_USER
          value: user
        - name: PMA_PASSWORD
          value: pw
        - name: MYSQL_ROOT_PASSWORD
          value: 1q2w3e4r
        ports: 
        - containerPort: 8080
          name: phpmyadmin
      - name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1q2w3e4r
        - name: TZ
          value: Asia/Taipei
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: pw
        image: mariadb
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-data
      volumes:
      - name: mariadb-data
        hostPath:
          path: /home/wzsdat/mariadb-data