# Custom node-exporter collecting GPU metrics from dcgm-exporter.
# Refer: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/prometheus/node-exporter-ds.yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      # nodeSelector:
      #   hardware-type: NVIDIAGPU
      containers:
      - image: harbor.wzs.wistron.com.cn/datteam/prom/node-exporter:v1.0.0
        name: node-exporter
        args:
        - "--web.listen-address=0.0.0.0:9100"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        - "--collector.textfile.directory=/run/prometheus"
        ports:
        - name: metrics
          containerPort: 9100
          # hostPort: 9100
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
        - name: collector-textfiles
          readOnly: true
          mountPath: /run/prometheus
      # - image: harbor.wzs.wistron.com.cn/nvidia/dcgm-exporter:1.4.6
      #   name: nvidia-dcgm-exporter
      #   securityContext:
      #     runAsNonRoot: false
      #     runAsUser: 0
      #   volumeMounts:
      #   - name: collector-textfiles
      #     mountPath: /run/prometheus
      # hostNetwork: true
      # hostPID: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: collector-textfiles
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app: node-exporter
spec:
  ports:
  - name: http
    port: 9100
    nodePort: 30091
    protocol: TCP
  type: NodePort
  selector:
    app: node-exporter