apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  # namespace: kube-system
spec:
  ports:
  - name: web
    # nodePort: 30090
    port: 8080
    targetPort: 8080
  selector:
    app: cadvisor
  type: NodePort