# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- svc_ss.yaml
commonLabels:
  app: grafana
images:
- name: grafana/grafana
  newName: harbor.wzs.wistron.com.cn/datteam/grafana/grafana
  newTag: 7.0.0-ubuntu
configMapGenerator:
- name: dashboards
  files:
  - ./dashboards/FTP-Metrics-P3-DC.json
  - ./dashboards/Loki-lowlight-log.json
  - ./dashboards/node-exporter-full_rev19.json
  - ./dashboards/P3-DIP-Prewave-AOI-INFA.json
- name: grafana-config
  files:
  - ./config/grafana.yml
  - ./config/grafana.ini
- name: dashboard-config
  files:
  - ./config/dashboard.yml
secretGenerator:
- name: grafana-env
  envs:
  - ./config/grafana.env
  type: Opaque
patchesStrategicMerge:
- externalIPs.yaml