apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
spec:
  template:
    spec:
      securityContext:
        runAsUser: 100
        fsGroup: 65533
      serviceAccountName: robert-gitlab-runner
      initContainers:
      - name: configure
        command: 
        - sh
        - /config/configure
        image: gitlab-runner
        imagePullPolicy: IfNotPresent
        env:
        # find additional config from:
        # https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/master/templates/_env_vars.tpl
        - name: RUNNER_EXECUTOR
          value: "kubernetes"
        - name: CI_SERVER_URL
          value: $CI_SERVER_URL
        - name: REGISTER_LOCKED
          value: "false"
        volumeMounts:
        - name: runner-secrets
          mountPath: /secrets
          readOnly: false
        - name: scripts
          mountPath: /config
          readOnly: true
        - name: init-runner-secrets
          mountPath: /init-secrets
          readOnly: true
      containers:
      - name: gitlab-runner
        command: 
        - /bin/bash
        - /scripts/entrypoint
        image: gitlab-runner
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2
            memory: 2Gi
        lifecycle:
          preStop:
            exec:
              command:
              - /entrypoint unregister --all-runners
        livenessProbe:
          exec:
            command: ["/bin/bash", "/scripts/check-live"]
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/usr/bin/pgrep","gitlab.*runner"]
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: CI_SERVER_URL
          value: $CI_SERVER_URL
        - name: RUNNER_EXECUTOR
          value: "kubernetes"
        - name: REGISTER_LOCKED
          value: "false"
        - name: KUBERNETES_CPU_LIMIT
          value: "2"
        - name: KUBERNETES_MEMORY_LIMIT
          value: "2Gi"
        - name: KUBERNETES_HELPER_CPU_LIMIT
          value: "2"
        - name: KUBERNETES_HELPER_MEMORY_LIMIT
          value: "2Gi"
        - name: KUBERNETES_PULL_POLICY
          value: always
        volumeMounts:
        - name: runner-secrets
          mountPath: /secrets
        - name: etc-gitlab-runner
          mountPath: /home/gitlab-runner/.gitlab-runner
        - name: scripts
          mountPath: /scripts
        - name: gitlab-k8s-runner-crt
          mountPath: /home/gitlab-runner/.gitlab-runner/certs/
      volumes:
      - name: runner-secrets
        emptyDir:
          medium: "Memory"
      - name: etc-gitlab-runner
        emptyDir:
          medium: "Memory"
      - name: scripts
        configMap:
          name: gitlab-runner
      - name: init-runner-secrets
        secret:
          secretName: gitlab-runner-registration-token
      - name: gitlab-k8s-runner-crt
        secret:
          secretName: gitlab-runner-ca
      hostAliases:
      - hostnames:
        - gitlab-k8s.wzs.wistron.com.cn
        ip: "10.41.241.138"
