apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-ftp
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ai-ftp
    namespace: default
    #hostPath:
    #  path: /home/wzsdat/ftp
    #  type: ""
  local:
    path: /ai
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - wcdai
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-ftp
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: ai-ftp
