apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  podMetadata:
    labels:
      role: monitoring
  image: harbor.wzs.wistron.com.cn/prometheus/prometheus:v2.13.0
  serviceAccountName: $(PROMETHEUS_SERVICE_ACCOUNT)
  serviceMonitorSelector:
    matchLabels:
      prometheus: $(PROMETHEUS_NAME)
  podMonitorSelector:
    matchLabels:
      prometheus: $(PROMETHEUS_NAME)
  enableAdminAPI: true
  retentionSize: 1GB
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi