apiVersion: v1
kind: Service
metadata:
  name: tfserving
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 32210
    targetPort: grpc
    nodePort: 32210
  - name: rest
    port: 32211
    targetPort: rest
    nodePort: 32211
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfserving
spec:
  selector: 
    matchLabels: 
      app: tfserving
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata: 
      labels: 
        app: tfserving
    spec:
      restartPolicy: Always
      containers: 
      - name: tfserving
        image: serving
        imagePullPolicy: IfNotPresent
        command:
        # - /usr/bin/tf_serving_entrypoint.sh
        - tensorflow_model_server
        args:
        - --model_config_file=/models/models.config
        - --monitoring_config_file=/model_config/monitoring_config.txt
        - --batching_parameters_file=/model_config/batching_pars.txt
        - --model_config_file_poll_wait_seconds=60
        - --file_system_poll_wait_seconds=65
        - --allow_version_labels_for_unavailable_models=true
        - --enable_batching=true
        - --enable_model_warmup=true
        - --tensorflow_intra_op_parallelism=$(CPULIMITS)
        - --tensorflow_inter_op_parallelism=$(CPULIMITS)
        env:
        - name: CPULIMITS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        ports:
        - name: grpc
          containerPort: 8500
        - name: rest
          containerPort: 8501
        volumeMounts:
        - name: ai-models
          mountPath: /models
        - name: model-config
          mountPath: /model_config
        livenessProbe:
          initialDelaySeconds: 80
          httpGet:
            path: /monitoring/prometheus/metrics
            port: rest
        readinessProbe:
          initialDelaySeconds: 80
          httpGet:
            path: /monitoring/prometheus/metrics
            port: rest
        resources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 4
            memory: 2Gi