# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- svc_ss.yaml
commonLabels:
  app: prometheus
  role: logging
images:
- name: prometheus
  newName: harbor.wzs.wistron.com.cn/prometheus/prometheus
  newTag: v2.13.0
configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml