apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: api
    port: 9090
    targetPort: api
    nodePort: 30090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceName: prometheus
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prometheus
        imagePullPolicy: IfNotPresent
        command:
        - /bin/prometheus
        args:
        - --config.file=/prometheus.yml
        - --storage.tsdb.path=/prometheus/data
        - --storage.tsdb.retention.time=30d
        - --storage.tsdb.retention.size=2GB
        # - --storage.local.series-file-shrink-ratio=0.3
        volumeMounts: 
        - name: prometheus-config
          mountPath: /prometheus.yml
          subPath: prometheus.yml
        - name: data
          mountPath: /prometheus/data
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          # limits:
          #   cpu: 1
          #   memory: 1Gi
        ports:
        - name: api
          containerPort: 9090
      volumes: 
      - name: prometheus-config
        configMap:
          name: prometheus-config
      # - name: prometheus-data
      #   hostPath:
      #   # the directory below should "chown nobody/nogroup", not be root/root
      #     path: /home/wzsdat/prometheus-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: "local-path"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi