apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: local
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: log-pv-space
  labels:
    app: pv
    space: log
spec: 
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  # local:
  #   path: /log
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ['172.30.52.10']
  hostPath:
    path: "/log"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  labels:
    app: pvc
    space: log
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      space: log