apiVersion: v1
kind: Service
metadata:
  name: tfserving
spec:
  type: NodePort
  externalIPs: 
  - 172.20.84.22
  - 10.62.13.152
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  externalIPs: 
  - 172.20.84.22
  - 10.62.13.152