apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template: 
    spec:
      containers:
      - name: gateway
        volumeMounts:
        - name: checkpoint
          mountPath: /config
          subPath: config
        - name: checkpoint
          mountPath: /checkpoint
        - name: aipredict
          mountPath: /IPBU_AIpredict
      volumes:
      - name: checkpoint
        emptyDir: {}
      - name: aipredict
        hostPath:
          path: /home/wzsdat/IPBU_AIpredict