apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  externalIPs: 
  - 172.30.52.10
  - 10.41.16.21
  ports:
  - name: gw
    port: 3333
    targetPort: gw
    nodePort: 30138