{
 "title": "INFA Gateway Metrics",
 "description": "project: aoi-ai",
 "tags": [
  "aoi-wzs-p3-dip-prewave-saiap",
  "gateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "MODEL_NAME",
    "query": "query_result(count by (model_name)(count_over_time(model_health{job=\"gateway\"}[$__range])))"
   },
   {
    "name": "pred_class",
    "label": "PRED_CLASS",
    "query": "query_result(count by (pred_class)(count_over_time(image_counter_total{job=\"gateway\"}[$__range])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "stat",
     "description": "requests count  \n(req_counter)",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(req_counter_total{job=\"gateway\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Total requested images",
     "type": "stat",
     "description": "total requested image amount.  \n(total_res_img_counter_total)",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(total_res_img_counter_total{job=\"gateway\"}[$__range]))"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 6, "y": 1 },
     "content": "##### MUST SELECT LABEL `MODEL_NAME`\n↓↓↓↓↓"
    },
    {
     "title": "Image Amount",
     "type": "bargauge",
     "description": "within time range by component, pred_class. \nimage_counter_total",
     "gridPos": { "h": 14, "w": 7, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(image_counter_total{job=\"gateway\"}[$__range])",
       "legendFormat": "{{ component }}: {{ pred_class }}"
      }
     ]
    },
    {
     "title": "Outline Images",
     "type": "bargauge",
     "description": "outline Images count by online models by time range.   \noutline_img_counter_total{model_name}\n\n",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(outline_img_counter_total{job=\"gateway\"}[$__range])",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "TFserving Secs Taken",
     "type": "stat",
     "description": "(MUST SELECT MODEL_NAME).  \n\navg. tfserving secs taken by var: model_name.  \n(predicts_duration_secs / inferred_img_counter)",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "increase(predicts_duration_secs_total{job=\"gateway\",model_name=\"$model_name\"}[$__range]) / increase(inferred_img_counter_total{job=\"gateway\",model_name=\"$model_name\"}[$__range])"
      }
     ]
    },
    {
     "title": "No Inferred Images",
     "type": "stat",
     "description": "request images of not online component   \n(no_infer_img_counter)",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(no_infer_img_counter_total{job=\"gateway\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Total re-judged images",
     "type": "stat",
     "description": "re-judged images which are online component.  \n(total_inferred_img_counter_total)",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(total_inferred_img_counter_total{job=\"gateway\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Seconds took per request",
     "type": "stat",
     "description": "seconds took per request by time range.   \n(pro_time_counter / req_counter_total)",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "increase(pro_time_counter_total{job=\"gateway\"}[$__range]) / increase(req_counter_total{job=\"gateway\"}[$__range])"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 6, "y": 8 },
     "content": "##### MUST SELECT LABEL `MODEL_NAME`, `PRED_CLASS`\n↓↓↓↓↓"
    },
    {
     "title": "Average Model Confidence",
     "type": "stat",
     "description": "(MUST SELECT MODEL_NAME, PRED_CLASS)  \n\navg. model confidence by model_name, pred_class.  \n(confidence_sum / inferred_img_counter)",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "increase(confidence_sum_total{job=\"gateway\",model_name=\"$model_name\",pred_class=\"$pred_class\"}[$__range]) / increase(predicts_img_counter_total{job=\"gateway\",model_name=\"$model_name\", pred_class=\"$pred_class\"}[$__range])"
      }
     ]
    },
    {
     "title": "Seconds took per response image",
     "type": "stat",
     "description": "seconds took per response image by time range.     \n(pro_time_counter / total_res_img_counter)",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "increase(pro_time_counter_total{job=\"gateway\"}[$__range]) / increase(total_res_img_counter_total{job=\"gateway\"}[$__range])"
      }
     ]
    },
    {
     "title": "Confidence",
     "type": "graph",
     "description": "rate by 2 min",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(confidence_sum_total{job=\"gateway\",model_name!=\"own-cap-all\"}[2m]) / rate(predicts_img_counter_total{job=\"gateway\",model_name!=\"own-cap-all\"}[2m])",
       "legendFormat": "{{model_name}}-{{pred_class}}"
      }
     ]
    },
    {
     "title": "images / min",
     "type": "graph",
     "description": "rate 1 min",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(image_counter_total{job=\"gateway\"}[1m])) by (component) * 60",
       "legendFormat": "{{component}}"
      }
     ]
    }
   ]
  },
  { "title": "Instant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Image Amount",
   "type": "stat",
   "description": "within selected time range",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (pred_class, component) (increase(image_counter_total{job=\"gateway\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Predicted Images by components",
   "type": "graph",
   "description": "components only include online model.  \n(image_counter)",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "number" }
   ],
   "targets": [
    {
     "expr": "sum without (pred_class) (increase(image_counter_total{job=\"gateway\"}[1y]))",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Model Health",
   "type": "graph",
   "description": "1: Healthy, 0: Offline  \nrequest get TF serving links.  \n(model_health)",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "health" }
   ],
   "targets": [
    {
     "expr": "model_health{job=\"gateway\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Inference Version",
   "type": "stat",
   "description": "Inference Version by model name.  \n(inference_version)",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inference_version{job=\"gateway\",model_name!=\"own-cap-all\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Seconds taken per Image",
   "type": "gauge",
   "description": "The latest request secs taken during server processing.  \n(sec_perimg_Gauge)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sec_perimg_Gauge{job=\"gateway\"}"
    }
   ]
  },
  {
   "title": "Errors Logs",
   "type": "logs",
   "description": "within time range",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{severity=\"error\"}"
    }
   ]
  },
  {
   "title": "requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(req_counter_total{job=\"gateway\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Online Model Version ",
   "type": "graph",
   "description": "1: Healthy, 0: Offline.  \nmodel bar would be flexible if loaded new version model.  \n(:tensorflow:cc:saved_model:load_attempt_count)",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": ":tensorflow:cc:saved_model:load_attempt_count{job=\"tfserving\"}",
     "legendFormat": "{{model_path}}:{{status}}"
    }
   ]
  }
 ]
}