apiVersion: v1
kind: Service
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  type: ClusterIP
  ports:
  - name: metrics
    port: 9080
    targetPort: metrics
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector: 
    matchLabels:
      app: promtail
  template:
    metadata: 
      labels: 
        app: promtail
    spec:
      serviceAccountName: promtail
      tolerations:
      - key: node-role.kubernetes.io/controlplane
        effect: NoSchedule
      - key: node-role.kubernetes.io/etcd
        effect: NoExecute
      containers:
      - name: promtail
        image: grafana/promtail
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/config.yaml
        # - -client.url=http://loki:3100/api/prom/push
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        ports:
        - name: metrics
          containerPort: 9080
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: promtail-config
          mountPath: /config.yaml
          subPath: config.yaml
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: promtail-config
        configMap:
          name: promtail-config