# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- deploy.yaml
commonLabels:
  app: vsftpd
images:
- name: vsftpd
  newName: harbor-k8s.wzs.wistron.com.cn/common/vsftpd
  newTag: v1
configMapGenerator:
- name: dgx2-aoi-ftp-prd-config
  files:
  - ./config/run-vsftpd.sh
  - ./config/virtual_users.txt
  - ./config/vsftpd.conf
  - ./config/vsftpd_conf_migrate.sh
# secretGenerator:
# - name: grafana-env
#   envs:
#   - ./config/grafana.env
#   type: Opaque
# patchesStrategicMerge:
# - externalIPs.yaml