# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- svc_ss.yaml
commonLabels:
  app: loki
  role: logging
images:
- name: grafana/loki
  newName: harbor.wzs.wistron.com.cn/datteam/grafana/loki
  newTag: 1.4.1
configMapGenerator:
- name: loki-config
  files:
  - config.yml