# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
bases:
- ../../base
commonLabels:
  app: tfserving
  project: aoi-wzs-p3-dip-prewave-saiap
  modelsfrom: gitlab
secretGenerator:
- name: gitlab-access-token
  envs:
  - gitlab.txt
  type: Opaque
patchesStrategicMerge:
- externalIPs.yaml
- gitlab_clone_pull.yaml
- deployment_volume.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 1Gi
  target:
    kind: Deployment
    name: tfserving