apiVersion: apps/v1
kind: Deployment
metadata:
  name: aoi-wzs-p3-dip-prewave-saiap-daily-metrics
  labels: 
    project: aoi-wzs-p3-dip-prewave-saiap
    app: daily-metrics
spec:
  strategy:
    type: RollingUpdate   
  replicas: 1
  selector:
    matchLabels:
        project: aoi-wzs-p3-dip-prewave-saiap
        app: daily-metrics
  template:
    metadata:
      labels:
        project: aoi-wzs-p3-dip-prewave-saiap
        app: daily-metrics
    spec:
      containers:
      - name: metrics
        image: harbor.wzs.wistron.com.cn/datteam/aoi-wzs-p3-dip-prewave-saiap/daily-metrics:latest
        workingDir: /app
        imagePullPolicy: Always
        env:
        - name: FTPHOST
          value: "10.41.241.5:30121"
        - name: USER
          value: "aoi-wzs-p3-dip-prewave-saiap"
        - name: PASSWORD
          value: "P3ftp@2020"
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits: # Maximum
            cpu: 500m
            memory: 500M
        # command: 
        #   - sh
        #   - run-go.sh