apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy_svc.yaml
# namePrefix: test-
commonLabels:
  app: jupyter
  maintainer: robert
images:
- name: nvidia-jupyter
  newName: nvcr.io/nvidia/tensorflow
  newTag: "20.10-tf2-py3"
patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30009
    - op: replace
      path: /spec/ports/1/nodePort
      value: 30010
  target:
    kind: Service
    name: tensorflow2-jupyter