apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template: 
    spec:
      containers:
      - name: gateway
        volumeMounts:
        - name: config-json
          mountPath: /config
        - name: ai-ftp
          subPath: checkpoint
          mountPath: /checkpoint
        - name: ai-ftp
          subPath: AIpredict
          mountPath: /AIpredict
      volumes:
      - name: config-json
        hostPath:
          path: /home/wzsdat/ftp
      - name: ai-ftp
        persistentVolumeClaim: 
          claimName: ai-ftp