apiVersion: v1
kind: Service
metadata:
  name: daily-metrics
  labels:
    app: daily-metrics
spec:
  type: ClusterIP
  selector:
    app: daily-metrics
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-metrics
  labels: 
    app: daily-metrics
spec:
  strategy:
    type: RollingUpdate   
  replicas: 1
  selector:
    matchLabels:
      app: daily-metrics
  template:
    metadata:
      labels:
        app: daily-metrics
    spec:
      containers:
      - name: metrics
        image: ftp-metrics
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef: 
            name: data-center-ftp
        env:
        - name: CRONDAYS
          value: "7"
        - name: IMGEXTENSION
          value: "png"    
        ports:
        - name: metrics
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits: 
            cpu: 100m
            memory: 100M
        # command: 
        #   - sh
        #   - run-go.sh