apiVersion: v1
data:
  USER: aoi-wzs-p3-dip-prewave-saiap
  PASSWORD: P3ftp@2020
  FTP: 10.41.241.5:30121
  SOURCE_DIR: dip-prewave-saiap
  IMAGE_FOLDER_PATH: /data/
kind: ConfigMap
metadata:
  name: aoi-wzs-p3-dip-prewave-saiap-ftp-cronjob-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aoi-wzs-p3-dip-prewave-saiap-pull-ftp-to-metadata
data:
  pull-ftp.sh: |
    cd ${IMAGE_FOLDER_PATH}

    wget \
        --user="${USER}" \
        --password="${PASSWORD}" \
        --cut-dirs=1 \
        -m -nH -nv \
        ftp://${FTP}/"${SOURCE_DIR}"