# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_process_pb2 as ai__process__pb2


class AIProcessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreProcess = channel.unary_unary(
                '/AIProcess/PreProcess',
                request_serializer=ai__process__pb2.ProcessRequest.SerializeToString,
                response_deserializer=ai__process__pb2.ProcessReply.FromString,
                )
        self.PostProcess = channel.unary_unary(
                '/AIProcess/PostProcess',
                request_serializer=ai__process__pb2.ProcessRequest.SerializeToString,
                response_deserializer=ai__process__pb2.ProcessReply.FromString,
                )


class AIProcessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PreProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIProcessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.PreProcess,
                    request_deserializer=ai__process__pb2.ProcessRequest.FromString,
                    response_serializer=ai__process__pb2.ProcessReply.SerializeToString,
            ),
            'PostProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.PostProcess,
                    request_deserializer=ai__process__pb2.ProcessRequest.FromString,
                    response_serializer=ai__process__pb2.ProcessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AIProcess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIProcess(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PreProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIProcess/PreProcess',
            ai__process__pb2.ProcessRequest.SerializeToString,
            ai__process__pb2.ProcessReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AIProcess/PostProcess',
            ai__process__pb2.ProcessRequest.SerializeToString,
            ai__process__pb2.ProcessReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
